### PR TITLE
Contributing docs (first cut).

### PR DESCRIPTION
**Pull request by pq**
A quick pass at some contributing docs.

To be clear, I'm sort of guessing at your process from perusing the repos and lines.  If I'm off base anywhere, do let me know.

And if you don't want such a doc, no worries at all either!

### CODE REVIEW

**Comment by pq** [comment]
@tehn @samdoshi 

Some notes for potential contributors (such as me ;)).  Feel free to ignore if this misses the mark!

**Comment by samdoshi** [comment]
Looks cool, though you could probably put most of that in the README.md instead?

I'd drop the Haskell bit, I only left the `euclidean.hs` file in there in case we need to regenerate the data.

Also, there seems to be some stuff about LGTM and flutter/engine in there!

**Comment by pq** [comment]
> Looks cool, though you could probably put most of that in the README.md instead?

Sounds good.  I'll move it over there instead.  Please stand-by. :smile: 

> Also, there seems to be some stuff about LGTM and flutter/engine in there!

D'oh!  Now you know where I cribbed that bit of text!  What's the process for getting a pull landed?  Just driven by the maintainers?

**Comment by samdoshi** [comment]
@pq, it's @tehn's baby, whatever he says goes.

The other option you've got is to add the contributing bits and bobs to the libavr32 repo, and then just post a link to it here in the readme.

(And if you fancied, adding the same link back to the other repos that use libavr32, earthsea, kria, meadowphysics & whitewhale. That would be supercool.)

**Comment by pq** [comment]
Thanks @samdoshi.  I addressed the bits you mentioned above but didn't merge it into the README pending feedback from @tehn.

Happy to make this more general purpose and put it into the `libavr32` repo and have pointers from clients.  Again, I'll wait for input from @tehn though.

Cheers!

**Comment by tehn** [comment]
this looks great!

i feel compelled not to maintain several almost-identical files in many
repositories-- perhaps this should be generalized and moved to `libavr32`
and then each module (ww/mp/etc) should have a note in its readme pointing
to the lib howto.

**Comment by pq** [comment]
Sounds good @tehn!

I'll generalize and put together another PR.

**Comment by pq** [comment]
Closing this one.  I'll follow-up with some fresh ones.

**Pull request closed without merging**
