### PR TITLE
update N op's note table to match ansible/libavr32

### PR DESCRIPTION
**Pull request by csboling**
#### What does this PR do?

This is a non-functional change toward the goal of ensure Teletype and Ansible use the same tuning table, see https://github.com/monome/libavr32/pull/54.

#### Provide links to any related discussion on [lines](https://llllllll.co/).

https://llllllll.co/t/ansible-bug-reports-official/12436/88

#### How should this be manually tested?

Test that `N` gives the same results before and after, e.g. I ran `L 0 P.END: P I N I` and compared 

#### Any background context you want to provide?

Ultimately the goal here is to get consistent pitch calculations between Teletype, Ansible midi modes, and Ansible grid/arc modes.

#### I have,
* [ ] updated `CHANGELOG.md`
* [ ] updated the documentation
* [ ] run `make format` on each commit

I have not, because nothing actually changed functionally in Teletype -- Ansible will be updated to use this same tuning table from libavr32.

### CODE REVIEW

**Comment by tehn** [comment]
just noticed that travis is failing this build--- but i figure you had it working?

i'm renaming the branches right now, in addition to moving the libavr32 repo... so was updating .travis.yml but could not identify a problem

**Comment by scanner-darkly** [comment]
i think makefile needs to be updated for /simulator and /tests to include music.o - was going to do that this weekend but if you get to it before that please go ahead.

you're moving libavr32?

**Comment by tehn** [comment]
sorry, typo! moving the avr32 build tarball after seeing a TODO in the travis yml ---- forked it from samdoshi

**Comment by csboling** [comment]
Oops, sorry about the failing tests. I should definitely be running them more regularly, easy for issues to slip through the cracks there.

**Comment by tehn** [comment]
luckily travis runs the test, so any PR should tell us if it's passing--- i think it's going to be pretty rare that it fails.

i just didn't see that travis flagged it as failing :)

**Pull request merged**
