### PR TITLE
Re-add commits lost due to squashing of PR #114

### PR DESCRIPTION
**Pull request by samdoshi**
#### What does this PR do?

Adds the commits lost due to the accidental squashing of PR #114

#### How should this be manually tested?

Doesn't need hardware testing as it makes no changes. But anyone interested can look over the commits and try to check this _actually_ re-adds the commits in the way that we want.

----

Can I get a sign of from:

 - @tehn 
 - @scanner-darkly 
 - @burnsauce 

before I merge this please. (Also, attn: @cmcavoy  and @jlmitch5.)

To the best of my knowledge, this will add back in the missing commits by creating 2 parallel branches of code that end up in more or less the same place. `git blame` appears to show the "individual commit branch" as it's more recent. My expectation is that `git bisect` will be usable for tracking down issues that haven arisen as part of the 2.1 process, but that care will have to be taken when choosing the start and end commits.

### CODE REVIEW

**Comment by samdoshi** [comment]
As mentioned by @jlmitch5 in the #114 thread, due to the way this is done, these commits will not show up under the `v1.2.0` tag, but will under any subsequent release.

**Comment by samdoshi** [comment]
@scanner-darkly if you can point me to a public branch of your grid OPs, I can do a quick test to check if it will rebase cleanly for you?

**Comment by scanner-darkly** [comment]
https://github.com/scanner-darkly/teletype/tree/grid2

looks like it should be okay from a quick glance: 
https://github.com/samdoshi/teletype/compare/squash-fix...scanner-darkly:grid2

i won't be able to take a closer look at this until later today (my partner has a surgery this morning), if you guys feel this looks good please go ahead and merge, it should be easy to re-add my stuff even if there are conflicts later.

**Comment by burnsauce** [comment]
Looks great!  Thanks again!

**Comment by jlmitch5** [comment]
@samdoshi there's no way to "rebase" this work so that appears on "top" of the 2.1.0 commit, is there?

It'd be cool if blame was working (as you stated, looks like it's [not](https://github.com/samdoshi/teletype/blame/squash-fix/module/edit_mode.c)).  That being said, it's not a huge deal and everything else seems to be as expected so 👍

**Comment by samdoshi** [comment]
@jlmitch5 poop, I did the merges the wrong way round, `blame` _should_ be working.

Will force push a new update to this PR.

**Comment by samdoshi** [comment]
Force pushed... `blame` working again. (Sorry everyone!)

I've also checked that: https://github.com/scanner-darkly/teletype/tree/grid2 rebases cleanly against this PR (it does).

I've got a poorly baby strapped to my chest at the moment... and he's requiring most of my attention. I'll do some more double checking once I have the space to think about it.

If anyone else cares to look, that would be great (the more eyeballs the better).

**Comment by burnsauce** [comment]
I checked that `git blame` shows correct commit / timestamp information for the changes I've made.  I also confirmed that `git diff master` output is empty, and that the branch builds correctly.

**Comment by samdoshi** [comment]
Ah well. The `blame` didn't take. But the commits are  in there if needed for `bisect`.

[And most importantly credit is given, where credit is due!](https://github.com/monome/teletype/graphs/contributors)

(@burnsauce I would quite like to be knocked off the top spot, hint, hint...)

**Comment by burnsauce** [comment]
I'm not sure the flash would handle that volume of code!  You've set a high bar.

I'll do my best 😁

**Comment by scanner-darkly** [comment]
is it safe for me to rebase at this point?

**Comment by samdoshi** [comment]
Yep

**Pull request merged**
