### PR TITLE
jf4.0 ops, maths docs fix

### PR DESCRIPTION
**Pull request by desolationjones**
#### What does this PR do?
Adds JF4.0 OPs and expands existing OPs where they might address channels on two concurrent JF.
Fixes a docs error for maths section from earlier PR (missing quote encapsulation).

#### Provide links to any related discussion on [lines](https://llllllll.co/).
https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/297

#### How should this be manually tested?
Attach a single JF and run `JF.ADDR 2` to move it to the 2nd JF address. Attach another JF which will remain on primary address.

`JF.SEL 1` or `2` should cause subsequent JF commands to affect the specified JF unit, as should the MODs `JF1:...` and `JF2:...`. Note that the selected address is treated as "primary" by subsequent OPs.
`JF0:...` MOD should cause the following command to execute on both JF units.

Knob and switch values getters (`JF.RAMP`, `JF.CURVE`, `JF.FM`, `JF.TSC`, `JF.SPEED`, `JF.INTONE`, and `JF.TIME`) should return values from the previously selected JF unit. `JF.TIME` and `JF.INTONE` will add their CV offsets as well.

Expanded channel addressing is: 0 = all channels primary JF, -1 = all channels both JF, 1..6 = primary channels, 7..12 = secondary channels. So `JF.TR -1 1` should fire all triggers on both units and `DEL.R 12 100: JF.TR + I 1 1` should sweep triggers across all 12 channels.

With `O.MIN 0` and `O.MAX 11`, calling `JF.POLY N O V 10` successively should make a chromatic walk-up. Notes will automatically switch between primary and secondary JF every 6 notes, regardless of how many voices are in use.

#### Any background context you want to provide?
I used [jf.lua](https://github.com/monome/crow/blob/main/lua/ii/jf.lua) as a guide for the I2C commands.
Unable to run "make format" in the Docker image (I hope to learn soon how to modify the image to include CLANG-FORMAT).

#### If the related Github issues aren't referenced in your commits, please link to them here.
N/A

#### I have,
* [x] updated `CHANGELOG.md`
* [x] updated the documentation
* [ ] run `make format` on each commit

### CODE REVIEW

**Comment by desolationjones** [comment]
Thanks to Teletype Discord user stvrgrs for beta testing the JF OPs, and to Trent for guidance!

**Comment by attejensen** [comment]
The firmware doesn't build after this merge:
../src/ops/justfriends.c: In function 'op_JF_ADDR_get':
../src/ops/justfriends.c:335: error: 'JF_ADDRESS' undeclared (first use in this function)
../src/ops/justfriends.c:335: note: each undeclared identifier is reported only once for each function it appears in
../src/ops/justfriends.c: In function 'op_JF_PITCH_get':
<snip>
../libavr32/asf/avr32/utils/make/Makefile.avr32.in:402: recipe for target '../src/ops/justfriends.o' failed
make[1]: *** [../src/ops/justfriends.o] Error 1
make[1]: Leaving directory '/target/module'
Makefile:24: recipe for target 'teletype.zip' failed
make: *** [teletype.zip] Error 2

**Comment by desolationjones** [comment]
There was a change to libavr last year for address naming. Let me double-check that my OPs conform to it.

**Comment by scanner-darkly** [comment]
@desolationjones - you need to submit the submodule update too so that it points to the latest libavr32 commit

**Comment by desolationjones** [comment]
No, the submodule is already correct. I need to correct line #335 of justfriends.c to read `uint8_t d[] = { JF_ADDR, a };` instead of `uint8_t d[] = { JF_ADDRESS, a };`

**Comment by desolationjones** [comment]
Ok it's a bit confusing (JF_ADDR is an address, JF_ADDRESS is a command) but I think everything looks good, and TT just isn't using the latest libavr32? I see
`#define JF_ADDRESS  14`
in libavr32's ii.h, but Teletype is pointing at the older 1f207dd libavr32 build. How do I correct that?

**Comment by tehn** [comment]
apologies, i did a visual code check, didn't compile.

**Comment by desolationjones** [comment]
@tehn no worries, obviously it compiled fine for me but I must have separately checked out the newest libavr32. Is the fix on my end or yours?

**Comment by scanner-darkly** [comment]
@desolationjones - yes, you need to update the submodule reference for `libavr32` (in fact, git status should show it as an uncommitted change). basically, whatever commit your local `libavr32` submodule currently has checked out is what your local build uses. if it differs from what the origin branch points to it's considered a submodule reference change. 

one thing you should make sure is that you are not changing the submodule repo to your own fork and that you are pointing to an existing commit in `libavr32`.

**Comment by scanner-darkly** [comment]
i've pushed a PR that should fix this. @attejensen @desolationjones want to give it a try?

**Comment by desolationjones** [comment]
Thanks @scanner-darkly, away from home but I'll test tonight.
It looks like my use of the dev-forsaken GitHub Desktop app failed me here as there is no `update submodule` option in it. Guess I should get reacquainted with the command line.

**Comment by scanner-darkly** [comment]
i really like git extensions, especially for making commits.

**Comment by attejensen** [comment]
build here now!

**Comment by attejensen** [comment]
should we test on the actual tt before being too confident? in any case, thanks for the swift action @scanner-darkly !!!!!

**Pull request merged**
