### PR TITLE
N.B and N.BX: disregard bits beyond bit 12 (except when negative, = presets)

### PR DESCRIPTION
**Pull request by attejensen**
#### What does this PR do?
setting scale with N.B or N.BX with 13-15 bits, will only use the first 12 bits, instead of R111111111111

#### Provide links to any related discussion on [lines](https://llllllll.co/).
https://llllllll.co/t/teletype-4-0-0-pre-release-beta-ready-for-testing/45871/45

#### How should this be manually tested?
N.B(X) r s, should only set first 12 bits (when s positive) 

#### I have,
* [ ] updated `CHANGELOG.md` and `whats_new.md`
* [ ] updated the documentation
* [ ] updated `help_mode.c` (if applicable)
* [ ] run `make format` on each commit
* [x] run tests

### CODE REVIEW

**Comment by scanner-darkly** [comment]
indentation seems off, could you run clang format? other than that looks good!

**Comment by desolationjones** [comment]
This will be a good test to see if the formatting messes up the `<<<` and `>>>` OPs again. Might need to turn off format for those affected sections.

**Comment by scanner-darkly** [comment]
good reminder - it will, even though it’s already surrounded with clang format off.
@attejensen - make sure to review the change after running format, it’ll likely change the op definition for `<<<` (or `>>>`, don’t remember).

also a good idea to run tests again after running clang format!

**Comment by desolationjones** [comment]
> good reminder - it will, even though it’s already surrounded with clang format off.

What good is the tag then 😅

**Comment by attejensen** [comment]
> indentation seems off, could you run clang format? other than that looks good!

I intentionally  didn't run make format, since it seemed to touch a lot of other peoples code, and I didn't want to clutter up this PR with that. How about someone else cleans this up in another PR and I'll make a fresh PR with only my changed + running make format?

**Comment by scanner-darkly** [comment]
i already ran format on all files as part of my last PR, so you just need to format the files you touched.

**Review by scanner-darkly — APPROVED** [review]

**Comment by attejensen** [comment]
Had to remove an inserted space in either line 276 or 277 (>>> or <<<), was that the issue I has to watch out for? Seems really horrible if this has to be hand-fixed + checked after every change+format of maths.c.....

> good reminder - it will, even though it’s already surrounded with clang format off.
> @attejensen - make sure to review the change after running format, it’ll likely change the op definition for `<<<` (or `>>>`, don’t remember).
> 
> also a good idea to run tests again after running clang format!

**Comment by scanner-darkly** [comment]
yeah that was the issue when i ran format.

**Pull request merged**
